matrix:
  include:
    - stage: auth
      language: java
      jdk:
        - oraclejdk8
      sudo: required
      before_install:
        - "cd auth"
        - chmod +x gradlew
        - chmod +x gradle/wrapper/gradle-wrapper.jar
        - gradle wrapper

    - stage: api
      jdk:
        - oraclejdk8
      language: java
      sudo: required
      before_install:
        - "cd api"
        - chmod +x gradlew
        - chmod +x gradle/wrapper/gradle-wrapper.jar
        - gradle wrapper
notifications:
  email:
    - mail@kutaycelebi.com