jobs:
  include:
    #region AUTH BUILD
    - stage: micro-services-build
      install: skip
      name: auth-build
      language: java
      sudo: required
      before_script:
        - "chmod +x gradlew"
        - "chmod +x gradle/wrapper/gradle-wrapper.jar"
        - "cd auth"
      script:
        - "./gradlew build"
    #endregion
    #region MICROSERVICES CORE
    - name: micro-services-core-build
      language: java
      sudo: required
      install: skip
      before_script:
        - "chmod +x gradlew"
        - "chmod +x gradle/wrapper/gradle-wrapper.jar"
        - "cd issue-tracker-api"
      script:
        - "./gradlew build"
    #endregion
    #region API BUILD
    - name: api-build
      language: java
      sudo: required
      install: skip
      before_script:
        - "chmod +x gradlew"
        - "chmod +x gradle/wrapper/gradle-wrapper.jar"
        - "cd issue-tracker-api"
      script:
        - "./gradlew build"
    #endregion
    #region DOC DEPLOYMENT
    - stage: docs-deployment
      branches:
        only:
          - master
      sudo: required
      before_install:
        - gem install bundler
        - "chmod +x gradlew"
        - "chmod +x gradle/wrapper/gradle-wrapper.jar"
      before_script:
        - "cd docs"
      script:
        - "./gradlew asciidoctor"
        - "./gradlew copyOutput --project-cache-dir=../cache"
      deploy:
        - provider: pages
          skip_cleanup: true
          local_dir: docs/build/docs/asciidoc/
          github_token: $GITHUB_TOKEN
          target_branch: gh-pages
          on:
            branch: master
    #endregion

#notifications:
#  email:
#    - mail@kutaycelebi.com