matrix:
  include:
    - language: java
      sudo: required
      before_script:
        - cd api
      before_install:
        - chmod +x api/gradlew
        - chmod +x api/gradle/wrapper/gradle-wrapper.jar
        - gradle wrapper
#notifications:
#  email:
#    - yourname@gmail.com