jobs:
  include:
    - name: auth-build
      language: java
      sudo: required
      before_script:
        - "cd auth"
        - chmod +x gradlew
        - chmod +x gradle/wrapper/gradle-wrapper.jar
      script:
        - "./gradlew build"
    - name: api-build
      language: java
      sudo: required
      before_script:
        - "cd api"
        - chmod +x gradlew
        - chmod +x gradle/wrapper/gradle-wrapper.jar
      script:
        - "./gradlew build"
    - name: build-docs
      branches:
        only:
          - master
      sudo: required
      before_script:
        - "cd docs"
        - chmod +x gradlew
        - chmod +x gradle/wrapper/gradle-wrapper.jar
      script:
        - "./gradlew asciidoctor"
        - "./gradlew copyOutput --project-cache-dir=../cache"
      after_success:
        - ./push.sh

#notifications:
#  email:
#    - mail@kutaycelebi.com