spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  security:
    user:
#      password: ${CONFIG_SERVICE_PASSWORD}
      password: 'test'

server:
  port: 8888

