version: "3"
services:
  db:
    image: "postgres"
    container_name: "postgresql"
    environment:
      - POSTGRES_USER=kuartz
      - POSTGRES_PASSWORD=k01.
      - POSTGRES_DB=mydb
    ports:
      - "54320:5432"
    networks:
      - test
networks:
  test:
    driver: bridge