server:
  port: 9999
spring:
  application:
    name: authz-service
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:54320/mydb}
    driver-class-name: org.postgresql.Driver
    username: ${DATASOURCE_USERNAME:kuartz}
    password: ${DATASOURCE_PASS:k01.}
    type: com.zaxxer.hikari.HikariDataSource
    initialization-mode: always
  jpa:
    hibernate:
      temp:
        use_jdbc_metadata_defaults: false
      ddl-auto: ${DDL_AUTO:create}
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        format_sql: false
  main:
    allow-bean-definition-overriding: true
kuartz:
  jpa:
    init:
      enable: true
      contive-on-error: true
      data-source:
        - yetki_init.sql
        - uaa_init.sql
logging:
  org.hibernate.SQL:
    level:
      -debug
  level:
    - error
    - warn
    - info
  # file: authz.log

eureka:
  client:
    serviceUrl:
      defaultZone: ${REGISTRY_SERVICE_URL:http://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true
---
spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: ${REGISTRY_SERVICE_URL:http://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true
  